version: '3.8'

services:
  cache:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - cache
    environment:
      - REDIS_URL=redis://cache:6379/0
